version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
    commands:
        - echo Entered the install phase...
        - apt-get update -y
  build:
    commands:
      - echo Entered the build phase...
      - make build